# Site settings
title: Nick Quinlan's Newsletter
name: Nick Quinlan
email: nick@nicholasquinlan.com
address: >
  1201 Masonic Ave,
  Apt A,
  Berkeley, CA 94706
description: > # this means to ignore newlines until "baseurl:"
  Hi I'm Nick, you can have a direct line to all my inane thinkings by signing up for my newsletter.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://newsletter.nicholasquinlan.com" # the base hostname & protocol for your site
twitter_username: yaynickq
github_username: nquinlan
sendgrid_widget_token: LE4%2B7rBwLY9nxSQFULZ%2F3y%2BvPnaBFUb%2FeJMTp22MJmnZhpmMyIGUnUyYfU5NhkyWPvgDwjCmZTId63mwUgf06g%3D%3D
timezone: America/Los_Angeles
permalink: :year-:month-:day
relative_permalinks: false

unsubscribe: "{{unsubscribe}}"

# Build settings
markdown: kramdown

# Post Defaults
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      unsubscribe: "#"